### ISSUE TITLE
Change prop label param

### ISSUE THREAD

**Issue by Correct-Syntax** [GimelStudio/GimelStudio#109]
Change the Property ``label`` param to be ``fpb_label`` so that ``label`` can be reserved for other things.

**Comment by Carlosbogo** [comment]
Hi, I would like to work on this, but this is the first time I contribute to this repository. 
Is the objective just to change the name of the property `label` to `fpb_label` wherever it appears? Could you give me an example on where it should be changed?

**Comment by Correct-Syntax** [comment]
Hi, thanks for your interest in contributing. 🙂

Yes, basically just change the ``label`` param wherever it appears in https://github.com/GimelStudio/GimelStudio/blob/master/src/gimelstudio/core/node/property.py to ``fpb_label``. This includes the base Property class.

**Comment by Correct-Syntax** [comment]
I should also note that the references to ``label`` in src/nodes will also need to be changed.
