### ISSUE TITLE
Could not detect OpenImageIO's Python version

### ISSUE THREAD

**Issue by krionical** [GimelStudio/GimelStudio#168]
**Describe the bug**
Trying to compile on Linux Mint 20.3 Uma python 3.9 results in Could not detect OpenImageIO's Python version.

**To Reproduce**
python3.9 build.py as per instructions. Everything runs then stops at this point after brew installs OpenImageIO.

**Expected behavior**
Executable of Gimel Studio should be made.

**Comment by Correct-Syntax** [comment]
Could you paste the output of running the script here? The exe should output to ``dist/GimelStudio/``

**Comment by Correct-Syntax** [comment]
Do you have multiple versions of Python installed on your system? (``python --version``)

**Comment by krionical** [comment]
> Could you paste the output of running the script here? The exe should output to `dist/GimelStudio/`

No output is produced  in dist/GimelStudio/ as everything halts after it fails to detect the python version.

**Comment by krionical** [comment]
> Do you have multiple versions of Python installed on your system and is the default version 3.9 (`python --version`)?

Yes, I have another version of python installed for python3--Python 3.8.10. That's why I am running python3.9 for build. It is not "default" as I'm not sure how the rest of the system might like python 3.9.

**Comment by krionical** [comment]
So I played around a little with the build script in python:


            # -- Confirm we have the right version ---
            oiioPyVer = os.path.basename(os.path.dirname(oiioPackage))
            if "3.9" not in oiioPyVer:
                print("Could not detect OpenImageIO's Python version.")
                sys.exit()
                
Clearly, this is the line the program is hitting when it stops. So, I tried commenting it out which didn't work out due to other calls to the variable. So, I set the version to 3.8 in the code and it still didn't find the value. My guess then is that the way that the way openimageio is being installed is, for some reason, not allowing the python version to come through or even apparently setting the version variable at all.

**Comment by krionical** [comment]
I'm closing this not because it was solved, but because it is evident to me development people are busy and I am going to delete it for now and try it again on down the road.
