### ISSUE TITLE
Preferences/Configuration Dialog

### ISSUE THREAD

**Issue by Correct-Syntax** [GimelStudio/GimelStudio#2]
Settings/tabs I am thinking we are going to include in the dialog, so far:

- [ ] Node wire curvature (e.g: 0 is straight, 8 is curved, etc)
- [ ] Maybe some settings for enabling/disabling node cache as it may not always be needed/wanted
- [ ] Node Manager (add/remove enable/disable available nodes)
- [ ] Enable/disable "experimental" features
- [ ] Toggle showing image thumbnails on nodes by default
- [ ] Fonts path (default could be the system font folder)
- [ ] Default output folder (default could be the home folder of the users computer)
- [ ] Whether to position the Add Node menu based on the cursor location or just have it static (placed at the bottom corner)
- [ ] Toggle showing the statusbar by default

**Comment by iwoithe** [comment]
## Categories in the preferences

***Note:** Nothing that I say in this issue is final*

General
Interface

Addons
Nodes

System
File Paths

**Comment by Correct-Syntax** [comment]
This seems pretty good, but I might remove the "Addons" category and add a "Templates" category . 

Technically, the nodes *are* like addons in Gimel Studio so I don't think we need a separate category for addons. @iwoithe, what did you have in mind for the "Addons" category? :)

The templates category would be for managing nodegraph templates. This is also where users can add there own/install shared templates from others.

**Comment by iwoithe** [comment]
The idea behind addons is in case someone wants to add something that isn't built in to Gimel Studio (e.g. a pixel editor) that will extend the functionallity of Gimel Studio further (note: the pixel editor was an example, and is not an actual suggestion).

**Comment by Correct-Syntax** [comment]
@iwoithe ah, I see. Good idea. Not sure implementation-wise how it would be done. Mainly, I am not sure what would define the end of the node api and the start of the addons api. Technically, the node api will have access to the viewport so a pixel editor could probably be implemented with it (though it would be contained in a specific node, obviously). Maybe clarify a bit further?

**Comment by Correct-Syntax** [comment]
For Node categories, for now we'll have: **Input, Output, Blend, Color, Convert, Adjust, Filter, Transform** and maybe eventually a special G'MIC or Effects category for the G'MIC fancy filters and stuff.

**Comment by Correct-Syntax** [comment]
Also, add a setting for UI Translations #7

**Comment by iwoithe** [comment]
> Also, add a setting for UI Translations

I will put this under the "Interface" settings.

**Comment by Correct-Syntax** [comment]
I think we should also "reserve" some space to allow for a label (note) that says something like: "_* Requires program restart"._ Some of the settings can be adjusted on-the-fly, but others will need a program restart in order to take effect.

**Comment by Correct-Syntax** [comment]
Just to note, this issue handles the UI side, while #10 handles the backend.

**Comment by Correct-Syntax** [comment]
@iwoithe I think we're pretty-much ready to start implementing this now. 😀

**Comment by iwoithe** [comment]
The current progress. Still a lot to do, but I've now got the basic "stacked layout" working. :slightly_smiling_face: 

https://user-images.githubusercontent.com/73422868/121855592-af6ac100-cd32-11eb-9beb-752afaab7505.mp4

**Comment by iwoithe** [comment]
I didn't have the time to post the second screenshot (done a couple hours after the video).

![preferences](https://user-images.githubusercontent.com/73422868/122880574-4bbb4600-d379-11eb-93aa-c67bdfc68532.png)

@Correct-Syntax I need to know if the size of the buttons and spacing is/looks correct. I also need to double check the colors.

**Comment by Correct-Syntax** [comment]
@iwoithe this is looking quite good. The button sizing might be slightly tall depending on the look we're going for here, but otherwise I like it. 😀 Yes, make sure to double-check the colors also.

If you would like, you could open your current progress as a PR as mark it as a draft. 

Since the dialog is something that we will add to I don't mind multiple PRs for getting it complete (e.g: one for implementing the main shell, etc)

One thing to note is that we will need an OK and Cancel button in the right bottom side of the window (unless you have an idea otherwise). I think I forgot to mention that...

**Comment by iwoithe** [comment]
> we will need an OK and Cancel

I must admit I kind of forgot about that. :confused:

> you could open your current progress as a PR as mark it as a draft.

I will do that when I get the time. :slightly_smiling_face:

**Comment by Correct-Syntax** [comment]
Something, I was thinking is: Should we separate out the Node Manager into a separate dialog? The advantage would be that it would be less clutter for the dialog with more focus on just the nodes. Just an idea 😀

**Comment by iwoithe** [comment]
I have a question about the title of the preferences dialog: should we rename it from ``User Preferences & Settings`` to ``Preferences``?

**Comment by Correct-Syntax** [comment]
I am not sure since I don't have full clarity on what the dialog will actually include right now (e.g: it seems that technically it is both settings and preferences, so I guess it would be up to us to decide what term we want to use. I was sorta covering both by having the title that way!). You could change it if you'd like. :)

**Comment by Correct-Syntax** [comment]
I also wanted to mention, in case you didn't see yet, that the dropdown widget, checkbox widget etc are now pretty much complete in gswidgetkit so you can start using them. Just make sure to use the latest version. 🚀

**Comment by iwoithe** [comment]
What is the difference in the definition of ``Preferences`` and ``Settings``?

**Comment by Correct-Syntax** [comment]
Preferences has more to do with making it to be as the user prefers, while settings is generally just something that has a default and can be changed (but isn't often changed) regarding the system or how the application works. It would be like Node wire curvature vs. Fonts path. Although, I don't think it matters that much as it's kinda left to preference (no pun intended) which one to use since there is not really a standard for it...

That's how I think of it. 😉 

You could take a look at https://stackoverflow.com/questions/2074384/options-settings-properties-configuration-preferences-when-and-why for some different opinions and some interesting definitions, but I've included some tidbits below:

> Users they just change settings in the menu, to decide how a function works in the application. Settings and Preferences usually don't appear in the same application. Tools that more for efficiency, use Settings more. Applications that more for conveniency, use Preferences would be more friendly for users.

> Options/Settings are usually a more global property. In addition, Preferences are probably not things that have as large of an impact as something labeled options or settings. Things such as a minor change in the display or something similar.

> In truth it doesn't really matter so long as your expected audience understands what you mean.

So, whatever you would like @iwoithe I am okay with. 😃

**Comment by Correct-Syntax** [comment]
Okay, the app config backend should be implemented enough to where it can be attached to the dialog, etc.
