### ISSUE TITLE
Test and make fixes for MacOs

### ISSUE THREAD

**Issue by Correct-Syntax** [GimelStudio/GimelStudio#33]
Just as simple as that: just build and test on a MacOs system to see what needs to be fixed, etc. The current developers do not have access to a Mac so we need someone else to do this.

**Comment by yasuomaidana** [comment]
I could do it.

**Comment by Correct-Syntax** [comment]
Thank you for helping us out with this. Yes, these errors are helpful. Does the window come up okay?

**Comment by yasuomaidana** [comment]
Yes the windows opens 
![image](https://user-images.githubusercontent.com/32581141/122094728-168b8280-cdd2-11eb-87b2-dc4d0557b9d7.png)

**Comment by Correct-Syntax** [comment]
Thank you.

The errors point to something wrong with https://github.com/GimelStudio/gswidgetkit. Could you run the demo in that repo to see what kind of errors we get?

**Comment by Correct-Syntax** [comment]
The error about OpenImageIO is normal. It is the other errors I am trying to figure out.

**Comment by yasuomaidana** [comment]
Look I just run gswidgetkit and I got this errors
![image](https://user-images.githubusercontent.com/32581141/122096237-f492ff80-cdd3-11eb-99cd-3b3259dd89f8.png)
However the window opens, the thing is some elements fails, for example the opacity bar.
However the buttons seems to be okay
![image](https://user-images.githubusercontent.com/32581141/122096461-3754d780-cdd4-11eb-8823-9f5c0d8564a2.png)

**Comment by Correct-Syntax** [comment]
Could you try commenting out line 166 through 169 and re-running the program (at https://github.com/GimelStudio/gswidgetkit/blob/031ca6850c219060629793ad535110380f683d5c/gswidgetkit/number_field.py#L166)

**Comment by yasuomaidana** [comment]
I identified that this issue happens when you try to drag the bars

**Comment by Correct-Syntax** [comment]
@yasuomaidana does the issue still happen if you comment out line 166 through 169 in ```number_field.py```?

**Comment by yasuomaidana** [comment]
Yes, it seems that is an issue related to recursion depth 
![image](https://user-images.githubusercontent.com/32581141/122113616-f4046400-cde7-11eb-84ed-f4892add3914.png)

**Comment by Correct-Syntax** [comment]
Indeed. 

Try commenting out line 82 https://github.com/GimelStudio/gswidgetkit/blob/031ca6850c219060629793ad535110380f683d5c/gswidgetkit/number_field.py#L82

That way we can narrow the issue down to a problem with that method.

**Comment by Correct-Syntax** [comment]
What's strange is that this is not an issue on Windows or Linux that I know of, so it is specific to MacOs...

The recursion error means something is getting called over and over and stuck in a loop.

**Comment by Correct-Syntax** [comment]
@yasuomaidana I made some changes. See if changing  the ```OnLeftDown``` method to:

```python
    def OnLeftDown(self, event):
        pos = event.GetPosition()
        self.anchor_point = (pos[0], pos[1])
        self.changing_value = True
        self.parent.SetDoubleBuffered(True)
        self.UpdateDrawing()


```

works better.

It seems to work better than before, testing on Windows.

**Comment by yasuomaidana** [comment]
Yes it improved a lot the bar update. However the issue with recursion is still there

**Comment by Correct-Syntax** [comment]
I will have to take a deeper look into this and get back to you. 

Thanks for your help so far @yasuomaidana. 😄

**Comment by Correct-Syntax** [comment]
The only problem is that since no errors show up it's difficult for me to debug and tell whether it's working.

```python
    def OnMouseMotion(self, event):
        """
        When the mouse moves, it check to see if it is a drag, or if left down had happened.
        If neither of those cases are true then it will cancel the action.
        If they are true then it calculates the change in position of the mouse, then changes
        the position of the cursor back to where the left click event happened.
        """
        # Changes the cursor
        if self.changing_value:
            self.SetCursor(wx.Cursor(wx.CURSOR_BLANK))
        else:
            self.SetCursor(wx.Cursor(wx.CURSOR_SIZEWE))

        # Calculate the change in mouse position
        cur_point = event.GetPosition()
        self.delta = cur_point[self.scroll_dir] - self.anchor_point[self.scroll_dir]

        # If the cursor is being moved and dragged left or right
        if self.delta != 0 and event.Dragging() and self.changing_value:
            self.UpdateWidget()
            self.UpdateDrawing()

        if event.Dragging() and self.changing_value:
            self.SetCursor(wx.Cursor(wx.CURSOR_BLANK))
            # Set the cursor back to the original point so it doesn't run away
            self.WarpPointer(int(self.anchor_point[0]), int(self.anchor_point[1]))

        # Case where the mouse is moving over the control, but has no
        # intent to actually change the value
        if self.changing_value and not event.Dragging():
            self.changing_value = False
            self.parent.SetDoubleBuffered(False)
```

Maybe try the above code to see if that works?

**Comment by yasuomaidana** [comment]
It seems to be something related with the time that it takes to finish some functions. I insert some print functions and the delays that they inserts were enough to solve the issue. I'm looking the way to make that some parts of the code waits until resolve before to continue. However, I don't know if it could create new problems, so I'll check it before.

**Comment by yasuomaidana** [comment]
> The only problem is that since no errors show up it's difficult for me to debug and tell whether it's working.
> 
> ```python
>     def OnMouseMotion(self, event):
>         """
>         When the mouse moves, it check to see if it is a drag, or if left down had happened.
>         If neither of those cases are true then it will cancel the action.
>         If they are true then it calculates the change in position of the mouse, then changes
>         the position of the cursor back to where the left click event happened.
>         """
>         # Changes the cursor
>         if self.changing_value:
>             self.SetCursor(wx.Cursor(wx.CURSOR_BLANK))
>         else:
>             self.SetCursor(wx.Cursor(wx.CURSOR_SIZEWE))
> 
>         # Calculate the change in mouse position
>         cur_point = event.GetPosition()
>         self.delta = cur_point[self.scroll_dir] - self.anchor_point[self.scroll_dir]
> 
>         # If the cursor is being moved and dragged left or right
>         if self.delta != 0 and event.Dragging() and self.changing_value:
>             self.UpdateWidget()
>             self.UpdateDrawing()
> 
>         if event.Dragging() and self.changing_value:
>             self.SetCursor(wx.Cursor(wx.CURSOR_BLANK))
>             # Set the cursor back to the original point so it doesn't run away
>             self.WarpPointer(int(self.anchor_point[0]), int(self.anchor_point[1]))
> 
>         # Case where the mouse is moving over the control, but has no
>         # intent to actually change the value
>         if self.changing_value and not event.Dragging():
>             self.changing_value = False
>             self.parent.SetDoubleBuffered(False)
> ```
> 
> Maybe try the above code to see if that works?

It didn't work. 😞

**Comment by Correct-Syntax** [comment]
> It seems to be something related with the time that it takes to finish some functions. I insert some print functions and the delays that they inserts were enough to solve the issue.

Where did you insert the print statements? That might give a hint as to what the problem is.

**Comment by yasuomaidana** [comment]
I inserted them here
```python
# If the cursor is being moved and dragged left or right
        if self.delta != 0 and event.Dragging() and self.changing_value:
            self.UpdateWidget()
            self.UpdateDrawing()
            print("a")
        if event.Dragging() and self.changing_value:
            self.SetCursor(wx.Cursor(wx.CURSOR_SIZEWE))
            # Set the cursor back to the original point so it doesn't run away
            self.WarpPointer(int(self.anchor_point[0]), int(self.anchor_point[1]))
            print("b")
        # Case where the mouse is moving over the control, but has no
        # intent to actually change the value
        elif self.changing_value and not event.Dragging():
            self.changing_value = False
            self.parent.SetDoubleBuffered(False)
            print("c")
```

**Comment by Correct-Syntax** [comment]
That is very weird. On Windows it causes the cursor to flicker (so it's worse than before) so I wonder why adding print statements has something to do with it on MacOs.

From my research, a you mentioned it seems to have to do with paints to the window being called before the last one finishes.

In plain language I think that means you may want to try moving the ```self.UpdateDrawing()``` call around and see if that helps.

**Comment by yasuomaidana** [comment]
I used multithreading to solve this issue.

**Comment by Correct-Syntax** [comment]
@yasuomaidana, first thanks again for helping out. Sorry for the late reply as I have been offline this week. I am glad to see that you're making progress on this and excited for the MacOs version. 👍 

Is it possible for you to join either the Gimel Studio [Discord server](https://discord.gg/RqwbDrVDpK) or the [Gitter community](https://gitter.im/Gimel-Studio/community)? This way we can chat a bit about this, share images and video, etc easier than trying to do it in this Github issue. Please let me know what works for you.

**Comment by Correct-Syntax** [comment]
I have asked a question about the widget issue on the offical wxpython forum: https://discuss.wxpython.org/t/recursion-error-on-macos-with-custom-widget/35424

**Comment by Correct-Syntax** [comment]
Maybe try the following as suggested in the forum answer:

```python
    def UpdateDrawing(self):
        dc = wx.BufferedDC(wx.ClientDC(self), self.buffer)
        self.OnDrawBackground(dc)
        self.OnDrawWidget(dc)
```

I hope it works! 😄

**Comment by yasuomaidana** [comment]
Yes it worked, I implemented this function with my solution and seemed well

**Comment by Correct-Syntax** [comment]
Great! 😄 I will take a look a bit later. 

Anything else as far as issues on MacOs?

**Comment by Correct-Syntax** [comment]
@yasuomaidana could you try the below code. I made some adjustments but left some stuff commented out so that you could re-introduce them if needed. 

I am hoping to not have to rely on threading in order to solve this issue. Hopefully it will work now.

Also, thanks for your perseverance through this issue. 👍 

```python
import wx
from wx.lib.newevent import NewCommandEvent
from .textctrl import TextCtrl

numberfield_cmd_event, EVT_NUMBERFIELD = NewCommandEvent()
numberfield_change_cmd_event, EVT_NUMBERFIELD_CHANGE = NewCommandEvent()


def GetTextExtent(text):
    tdc = wx.WindowDC(wx.GetApp().GetTopWindow())
    w, h = tdc.GetTextExtent(text)
    return w, h


class NumberField(wx.Control):
    def __init__(self, parent, _id=wx.ID_ANY, label="", default_value=0, min_value=0,
                 max_value=10, suffix="px", show_p=True, scroll_horz=True, size=wx.DefaultSize):
        wx.Control.__init__(self, parent, _id, pos=wx.DefaultPosition,
                            size=size, style=wx.NO_BORDER)

        self.parent = parent
        self.focused = False
        self.mouse_in = False
        self.control_size = wx.DefaultSize
        self.show_p = show_p
        self.buffer = None
        self.dragging = False
        if scroll_horz is True:
            self.scroll_dir = 0
        else:
            self.scroll_dir = 1

        self.cur_value = default_value
        self.min_value = min_value
        self.max_value = max_value
        self.change_rate = .5
        self.change_value = 0
        self.suffix = suffix
        self.value_range = [i for i in range(min_value, max_value)]
        self.label = label

        self.padding_x = 20
        self.padding_y = 10

        # Flag that is true if a drag is happening after a left click
        self.changing_value = False

        # Keep track of last sent event
        self.last_sent_event = None

        # The point in which the cursor gets anchored to during the drag event
        self.anchor_point = (0, 0)

        # Text ctrl
        self.textctrl = TextCtrl(self, value=str(self.cur_value),
                                 style=wx.BORDER_NONE, pos=(0, 0),
                                 size=(10, 24))
        self.textctrl.Hide()

        self.textctrl.Bind(wx.EVT_LEAVE_WINDOW, self.OnHideTextCtrl)
        self.textctrl.Bind(wx.EVT_KILL_FOCUS, self.OnHideTextCtrl)

        self.Bind(wx.EVT_PAINT, self.OnPaint)
        self.Bind(wx.EVT_ERASE_BACKGROUND, lambda x: None)
        self.Bind(wx.EVT_MOTION, self.OnMouseMotion)
        self.Bind(wx.EVT_LEFT_DOWN, self.OnLeftDown, self)
        self.Bind(wx.EVT_LEFT_UP, self.OnLeftUp, self)
        self.Bind(wx.EVT_SET_FOCUS, self.OnSetFocus)
        self.Bind(wx.EVT_KILL_FOCUS, self.OnKillFocus)
        self.Bind(wx.EVT_LEAVE_WINDOW, self.OnMouseLeave)
        self.Bind(wx.EVT_ENTER_WINDOW, self.OnMouseEnter)
        self.Bind(wx.EVT_LEFT_DCLICK, self.OnShowTextCtrl)
        self.Bind(wx.EVT_SIZE, self.OnSize)

    def OnPaint(self, event):
        wx.BufferedPaintDC(self, self.buffer)

    def OnSize(self, event):
        size = self.GetClientSize()

        # Make sure size is at least 1px to avoid
        # strange "invalid bitmap size" errors.
        if size[0] < 1:
            size = (1, 1)
        self.buffer = wx.Bitmap(*size)
        self.UpdateDrawing()

    def UpdateDrawing(self):
        dc = wx.BufferedDC(wx.ClientDC(self), self.buffer)
        self.OnDrawBackground(dc)
        self.OnDrawWidget(dc)

    def OnDrawBackground(self, dc):
        dc.SetBackground(wx.Brush(self.parent.GetBackgroundColour()))
        dc.Clear()

    def OnDrawWidget(self, dc):
        fnt = self.parent.GetFont()
        dc.SetFont(fnt)
        dc.SetPen(wx.TRANSPARENT_PEN)

        full_val_lbl = str(self.cur_value)+self.suffix

        width = self.Size[0]
        height = self.Size[1]

        one_val = width / self.max_value
        self.p_val = round((self.cur_value*one_val))

        if self.mouse_in:
            dc.SetTextForeground("#ffffff")
            dc.SetBrush(wx.Brush(wx.Colour("#4c4c4c")))
        else:
            dc.SetTextForeground("#e9e9e9")
            dc.SetBrush(wx.Brush(wx.Colour("#333333")))
        dc.DrawRoundedRectangle(0, 0, width, height, 4)

        if self.show_p is True:
            dc.SetBrush(wx.Brush(wx.Colour("#5680C2")))
            dc.DrawRoundedRectangle(0, 0, self.p_val, height, 4)

            if self.p_val < width-4 and self.p_val > 4:
                dc.DrawRectangle((self.p_val)-4, 0, 4, height)

        lbl_w, lbl_h = GetTextExtent(self.label)
        val_w, val_h = GetTextExtent(full_val_lbl)

        dc.DrawText(self.label, self.padding_x, int((height/2) - (lbl_h/2)))
        dc.DrawText(full_val_lbl, (width-self.padding_x) - (val_w), int((height/2) - (val_h/2)))

        # Update position of textctrl
        self.textctrl.SetPosition((5, (int(self.Size[1]/2) - 10)))
        self.textctrl.SetSize((int(self.Size[0]-10), 24))
        self.textctrl.SetCurrentPos(len(str(self.cur_value)))

    # def updateDelta(self,event):
    #     # Calculate the change in mouse position
    #     cur_point = event.GetPosition()
    #     self.delta = cur_point[self.scroll_dir] - self.anchor_point[self.scroll_dir]
    # def updateDragging(self,event):
    #     self.dragging = event.Dragging()

    def OnMouseMotion(self, event):
        """
        When the mouse moves, it check to see if it is a drag, or if left down had happened.
        If neither of those cases are true then it will cancel the action.
        If they are true then it calculates the change in position of the mouse, then changes
        the position of the cursor back to where the left click event happened.
        """
        # Changes the cursor
        if self.changing_value:
            self.SetCursor(wx.Cursor(wx.CURSOR_BLANK))
        else:
            self.SetCursor(wx.Cursor(wx.CURSOR_SIZEWE))

        # Calculate the change in mouse position
        cur_point = event.GetPosition()
        self.delta = cur_point[self.scroll_dir] - self.anchor_point[self.scroll_dir]

        # T2 = threading.Thread(target=self.updateDelta,args=(event,))
        # T3 = threading.Thread(target=self.updateDragging,args=(event,))
        # T1.start()
        # T2.start()
        # T3.start()
        # T2.join()
        # T1.join()
        # T3.join()
        # If the cursor is being moved and dragged left or right
        if self.delta != 0 and event.Dragging() and self.changing_value:
            #T4 = threading.Thread(target=self.UpdateWidget)
            self.UpdateWidget()
            #T5 = threading.Thread(target=self.UpdateDrawing)
            self.UpdateDrawing()

        if event.Dragging() and self.changing_value:
            self.SetCursor(wx.Cursor(wx.CURSOR_BLANK))
            # Set the cursor back to the original point so it doesn't run away
            if 'wxMac' not in wx.PlatformInfo:
                self.WarpPointer(int(self.anchor_point[0]), int(self.anchor_point[1]))

        # Case where the mouse is moving over the control, but has no
        # intent to actually change the value
        if self.changing_value and not event.Dragging():
            self.changing_value = False
            self.parent.SetDoubleBuffered(False)
        #     T4.start()
        #     T4.join()
        #     del(T4)
        # del(T1,T2,T3)

    def OnHideTextCtrl(self, event):
        value = self.textctrl.GetValue()
        if value != " ":
            new_value = int(value)
            if new_value in [i for i in range(0, self.max_value+1)]:
                if new_value >= self.min_value and new_value <= self.max_value:
                    self.cur_value = new_value
        self.textctrl.Hide()
        self.SendChangeEvent()
        self.SendSliderEvent()
        self.UpdateDrawing()

    def OnShowTextCtrl(self, event):
        if self.show_p is False:
            self.textctrl.Show()
            self.textctrl.SetFocus()

    def SendSliderEvent(self):
        wx.PostEvent(self, numberfield_cmd_event(id=self.GetId(), value=self.cur_value))

    def SendChangeEvent(self):
        # Implement a debounce system where only one event is
        # sent only if the value actually changed.
        if self.cur_value != self.last_sent_event:
            wx.PostEvent(self, numberfield_change_cmd_event(
                                    id=self.GetId(), value=self.cur_value))
            self.last_sent_event = self.cur_value

    def Increasing(self):
        if self.delta > 0:
            return True
        else:
            return False

    def Decreasing(self):
        if self.delta < 0:
            return True
        else:
            return False

    def OnLeftUp(self, event):
        """
        Cancels the changing event, and turns off the optimization buffering
        """
        self.changing_value = False
        self.parent.SetDoubleBuffered(False)
        self.SetCursor(wx.Cursor(wx.CURSOR_SIZEWE))
        self.SendSliderEvent()

    def OnLeftDown(self, event):
        """
        Sets the anchor point that the cursor will go back to the original position.
        Also turns on the doublebuffering which eliminates the flickering when rapidly changing values.
        """
        pos = event.GetPosition()
        self.anchor_point = (pos[0], pos[1])
        self.changing_value = True
        self.parent.SetDoubleBuffered(True)
        self.UpdateDrawing()

    def OnSetFocus(self, event):
        self.focused = True
        self.Refresh()

    def OnKillFocus(self, event):
        self.focused = False
        self.Refresh()

    def OnMouseEnter(self, event):
        self.mouse_in = True
        self.Refresh()
        self.UpdateDrawing()

    def OnMouseLeave(self, event):
        """
        In the event that the mouse is moved fast enough to leave the bounds of the label, this
        will be triggered, warping the cursor back to where the left click event originally
        happened
        """
        if self.changing_value:
            self.WarpPointer(self.anchor_point[0], self.anchor_point[1])
        self.mouse_in = False
        self.Refresh()
        self.UpdateDrawing()

    def AcceptsFocusFromKeyboard(self):
        """Overridden base class virtual."""
        return True

    def AcceptsFocus(self):
        """ Overridden base class virtual. """
        return True

    def HasFocus(self):
        """ Returns whether or not we have the focus. """
        return self.focused

    def GetValue(self):
        return self.cur_value

    def SetValue(self, value):
        self.cur_value = value

    def SetLabel(self, label):
        self.label = label

    def UpdateWidget(self):
        self.change_value += self.change_rate/2.0

        if self.change_value >= 1:
            if self.Increasing():
                if self.cur_value < self.max_value:
                    self.cur_value += 1
            else:
                if (self.cur_value - 1) >= 0:
                    if self.cur_value > self.min_value:
                        self.cur_value -= 1

            # Reset the change value since the value was just changed.
            self.change_value = 0

        self.SendChangeEvent()

    def DoGetBestSize(self):
        """
        Overridden base class virtual.  Determines the best size of the control
        based on the label size, the bitmap size and the current font.
        """

        normal_label = self.label
        value_label = str(self.cur_value)+self.suffix

        font = wx.SystemSettings.GetFont(wx.SYS_DEFAULT_GUI_FONT)

        dc = wx.ClientDC(self)
        dc.SetFont(font)

        # Measure our labels
        lbl_text_w, lbl_text_h = dc.GetTextExtent(normal_label)
        val_text_w, val_text_h = dc.GetTextExtent(value_label)

        totalwidth = lbl_text_w + val_text_w + self.padding_x + 76

        # To avoid issues with drawing the control properly, we
        # always make sure the width is an even number.
        if totalwidth % 2:
            totalwidth -= 1
        totalheight = lbl_text_h + self.padding_y

        best = wx.Size(totalwidth, totalheight)

        # Cache the best size so it doesn't need to be calculated again,
        # at least until some properties of the window change
        self.CacheBestSize(best)

        return best
```

**Comment by yasuomaidana** [comment]
It worked fine. 

> @yasuomaidana could you try the below code. I made some adjustments but left some stuff commented out so that you could re-introduce them if needed.
> 
> I am hoping to not have to rely on threading in order to solve this issue. Hopefully it will work now.
> 
> Also, thanks for your perseverance through this issue. 👍
> 
> ```python
> import wx
> from wx.lib.newevent import NewCommandEvent
> from .textctrl import TextCtrl
> 
> numberfield_cmd_event, EVT_NUMBERFIELD = NewCommandEvent()
> numberfield_change_cmd_event, EVT_NUMBERFIELD_CHANGE = NewCommandEvent()
> 
> 
> def GetTextExtent(text):
>     tdc = wx.WindowDC(wx.GetApp().GetTopWindow())
>     w, h = tdc.GetTextExtent(text)
>     return w, h
> 
> 
> class NumberField(wx.Control):
>     def __init__(self, parent, _id=wx.ID_ANY, label="", default_value=0, min_value=0,
>                  max_value=10, suffix="px", show_p=True, scroll_horz=True, size=wx.DefaultSize):
>         wx.Control.__init__(self, parent, _id, pos=wx.DefaultPosition,
>                             size=size, style=wx.NO_BORDER)
> 
>         self.parent = parent
>         self.focused = False
>         self.mouse_in = False
>         self.control_size = wx.DefaultSize
>         self.show_p = show_p
>         self.buffer = None
>         self.dragging = False
>         if scroll_horz is True:
>             self.scroll_dir = 0
>         else:
>             self.scroll_dir = 1
> 
>         self.cur_value = default_value
>         self.min_value = min_value
>         self.max_value = max_value
>         self.change_rate = .5
>         self.change_value = 0
>         self.suffix = suffix
>         self.value_range = [i for i in range(min_value, max_value)]
>         self.label = label
> 
>         self.padding_x = 20
>         self.padding_y = 10
> 
>         # Flag that is true if a drag is happening after a left click
>         self.changing_value = False
> 
>         # Keep track of last sent event
>         self.last_sent_event = None
> 
>         # The point in which the cursor gets anchored to during the drag event
>         self.anchor_point = (0, 0)
> 
>         # Text ctrl
>         self.textctrl = TextCtrl(self, value=str(self.cur_value),
>                                  style=wx.BORDER_NONE, pos=(0, 0),
>                                  size=(10, 24))
>         self.textctrl.Hide()
> 
>         self.textctrl.Bind(wx.EVT_LEAVE_WINDOW, self.OnHideTextCtrl)
>         self.textctrl.Bind(wx.EVT_KILL_FOCUS, self.OnHideTextCtrl)
> 
>         self.Bind(wx.EVT_PAINT, self.OnPaint)
>         self.Bind(wx.EVT_ERASE_BACKGROUND, lambda x: None)
>         self.Bind(wx.EVT_MOTION, self.OnMouseMotion)
>         self.Bind(wx.EVT_LEFT_DOWN, self.OnLeftDown, self)
>         self.Bind(wx.EVT_LEFT_UP, self.OnLeftUp, self)
>         self.Bind(wx.EVT_SET_FOCUS, self.OnSetFocus)
>         self.Bind(wx.EVT_KILL_FOCUS, self.OnKillFocus)
>         self.Bind(wx.EVT_LEAVE_WINDOW, self.OnMouseLeave)
>         self.Bind(wx.EVT_ENTER_WINDOW, self.OnMouseEnter)
>         self.Bind(wx.EVT_LEFT_DCLICK, self.OnShowTextCtrl)
>         self.Bind(wx.EVT_SIZE, self.OnSize)
> 
>     def OnPaint(self, event):
>         wx.BufferedPaintDC(self, self.buffer)
> 
>     def OnSize(self, event):
>         size = self.GetClientSize()
> 
>         # Make sure size is at least 1px to avoid
>         # strange "invalid bitmap size" errors.
>         if size[0] < 1:
>             size = (1, 1)
>         self.buffer = wx.Bitmap(*size)
>         self.UpdateDrawing()
> 
>     def UpdateDrawing(self):
>         dc = wx.BufferedDC(wx.ClientDC(self), self.buffer)
>         self.OnDrawBackground(dc)
>         self.OnDrawWidget(dc)
> 
>     def OnDrawBackground(self, dc):
>         dc.SetBackground(wx.Brush(self.parent.GetBackgroundColour()))
>         dc.Clear()
> 
>     def OnDrawWidget(self, dc):
>         fnt = self.parent.GetFont()
>         dc.SetFont(fnt)
>         dc.SetPen(wx.TRANSPARENT_PEN)
> 
>         full_val_lbl = str(self.cur_value)+self.suffix
> 
>         width = self.Size[0]
>         height = self.Size[1]
> 
>         one_val = width / self.max_value
>         self.p_val = round((self.cur_value*one_val))
> 
>         if self.mouse_in:
>             dc.SetTextForeground("#ffffff")
>             dc.SetBrush(wx.Brush(wx.Colour("#4c4c4c")))
>         else:
>             dc.SetTextForeground("#e9e9e9")
>             dc.SetBrush(wx.Brush(wx.Colour("#333333")))
>         dc.DrawRoundedRectangle(0, 0, width, height, 4)
> 
>         if self.show_p is True:
>             dc.SetBrush(wx.Brush(wx.Colour("#5680C2")))
>             dc.DrawRoundedRectangle(0, 0, self.p_val, height, 4)
> 
>             if self.p_val < width-4 and self.p_val > 4:
>                 dc.DrawRectangle((self.p_val)-4, 0, 4, height)
> 
>         lbl_w, lbl_h = GetTextExtent(self.label)
>         val_w, val_h = GetTextExtent(full_val_lbl)
> 
>         dc.DrawText(self.label, self.padding_x, int((height/2) - (lbl_h/2)))
>         dc.DrawText(full_val_lbl, (width-self.padding_x) - (val_w), int((height/2) - (val_h/2)))
> 
>         # Update position of textctrl
>         self.textctrl.SetPosition((5, (int(self.Size[1]/2) - 10)))
>         self.textctrl.SetSize((int(self.Size[0]-10), 24))
>         self.textctrl.SetCurrentPos(len(str(self.cur_value)))
> 
>     # def updateDelta(self,event):
>     #     # Calculate the change in mouse position
>     #     cur_point = event.GetPosition()
>     #     self.delta = cur_point[self.scroll_dir] - self.anchor_point[self.scroll_dir]
>     # def updateDragging(self,event):
>     #     self.dragging = event.Dragging()
> 
>     def OnMouseMotion(self, event):
>         """
>         When the mouse moves, it check to see if it is a drag, or if left down had happened.
>         If neither of those cases are true then it will cancel the action.
>         If they are true then it calculates the change in position of the mouse, then changes
>         the position of the cursor back to where the left click event happened.
>         """
>         # Changes the cursor
>         if self.changing_value:
>             self.SetCursor(wx.Cursor(wx.CURSOR_BLANK))
>         else:
>             self.SetCursor(wx.Cursor(wx.CURSOR_SIZEWE))
> 
>         # Calculate the change in mouse position
>         cur_point = event.GetPosition()
>         self.delta = cur_point[self.scroll_dir] - self.anchor_point[self.scroll_dir]
> 
>         # T2 = threading.Thread(target=self.updateDelta,args=(event,))
>         # T3 = threading.Thread(target=self.updateDragging,args=(event,))
>         # T1.start()
>         # T2.start()
>         # T3.start()
>         # T2.join()
>         # T1.join()
>         # T3.join()
>         # If the cursor is being moved and dragged left or right
>         if self.delta != 0 and event.Dragging() and self.changing_value:
>             #T4 = threading.Thread(target=self.UpdateWidget)
>             self.UpdateWidget()
>             #T5 = threading.Thread(target=self.UpdateDrawing)
>             self.UpdateDrawing()
> 
>         if event.Dragging() and self.changing_value:
>             self.SetCursor(wx.Cursor(wx.CURSOR_BLANK))
>             # Set the cursor back to the original point so it doesn't run away
>             if 'wxMac' not in wx.PlatformInfo:
>                 self.WarpPointer(int(self.anchor_point[0]), int(self.anchor_point[1]))
> 
>         # Case where the mouse is moving over the control, but has no
>         # intent to actually change the value
>         if self.changing_value and not event.Dragging():
>             self.changing_value = False
>             self.parent.SetDoubleBuffered(False)
>         #     T4.start()
>         #     T4.join()
>         #     del(T4)
>         # del(T1,T2,T3)
> 
>     def OnHideTextCtrl(self, event):
>         value = self.textctrl.GetValue()
>         if value != " ":
>             new_value = int(value)
>             if new_value in [i for i in range(0, self.max_value+1)]:
>                 if new_value >= self.min_value and new_value <= self.max_value:
>                     self.cur_value = new_value
>         self.textctrl.Hide()
>         self.SendChangeEvent()
>         self.SendSliderEvent()
>         self.UpdateDrawing()
> 
>     def OnShowTextCtrl(self, event):
>         if self.show_p is False:
>             self.textctrl.Show()
>             self.textctrl.SetFocus()
> 
>     def SendSliderEvent(self):
>         wx.PostEvent(self, numberfield_cmd_event(id=self.GetId(), value=self.cur_value))
> 
>     def SendChangeEvent(self):
>         # Implement a debounce system where only one event is
>         # sent only if the value actually changed.
>         if self.cur_value != self.last_sent_event:
>             wx.PostEvent(self, numberfield_change_cmd_event(
>                                     id=self.GetId(), value=self.cur_value))
>             self.last_sent_event = self.cur_value
> 
>     def Increasing(self):
>         if self.delta > 0:
>             return True
>         else:
>             return False
> 
>     def Decreasing(self):
>         if self.delta < 0:
>             return True
>         else:
>             return False
> 
>     def OnLeftUp(self, event):
>         """
>         Cancels the changing event, and turns off the optimization buffering
>         """
>         self.changing_value = False
>         self.parent.SetDoubleBuffered(False)
>         self.SetCursor(wx.Cursor(wx.CURSOR_SIZEWE))
>         self.SendSliderEvent()
> 
>     def OnLeftDown(self, event):
>         """
>         Sets the anchor point that the cursor will go back to the original position.
>         Also turns on the doublebuffering which eliminates the flickering when rapidly changing values.
>         """
>         pos = event.GetPosition()
>         self.anchor_point = (pos[0], pos[1])
>         self.changing_value = True
>         self.parent.SetDoubleBuffered(True)
>         self.UpdateDrawing()
> 
>     def OnSetFocus(self, event):
>         self.focused = True
>         self.Refresh()
> 
>     def OnKillFocus(self, event):
>         self.focused = False
>         self.Refresh()
> 
>     def OnMouseEnter(self, event):
>         self.mouse_in = True
>         self.Refresh()
>         self.UpdateDrawing()
> 
>     def OnMouseLeave(self, event):
>         """
>         In the event that the mouse is moved fast enough to leave the bounds of the label, this
>         will be triggered, warping the cursor back to where the left click event originally
>         happened
>         """
>         if self.changing_value:
>             self.WarpPointer(self.anchor_point[0], self.anchor_point[1])
>         self.mouse_in = False
>         self.Refresh()
>         self.UpdateDrawing()
> 
>     def AcceptsFocusFromKeyboard(self):
>         """Overridden base class virtual."""
>         return True
> 
>     def AcceptsFocus(self):
>         """ Overridden base class virtual. """
>         return True
> 
>     def HasFocus(self):
>         """ Returns whether or not we have the focus. """
>         return self.focused
> 
>     def GetValue(self):
>         return self.cur_value
> 
>     def SetValue(self, value):
>         self.cur_value = value
> 
>     def SetLabel(self, label):
>         self.label = label
> 
>     def UpdateWidget(self):
>         self.change_value += self.change_rate/2.0
> 
>         if self.change_value >= 1:
>             if self.Increasing():
>                 if self.cur_value < self.max_value:
>                     self.cur_value += 1
>             else:
>                 if (self.cur_value - 1) >= 0:
>                     if self.cur_value > self.min_value:
>                         self.cur_value -= 1
> 
>             # Reset the change value since the value was just changed.
>             self.change_value = 0
> 
>         self.SendChangeEvent()
> 
>     def DoGetBestSize(self):
>         """
>         Overridden base class virtual.  Determines the best size of the control
>         based on the label size, the bitmap size and the current font.
>         """
> 
>         normal_label = self.label
>         value_label = str(self.cur_value)+self.suffix
> 
>         font = wx.SystemSettings.GetFont(wx.SYS_DEFAULT_GUI_FONT)
> 
>         dc = wx.ClientDC(self)
>         dc.SetFont(font)
> 
>         # Measure our labels
>         lbl_text_w, lbl_text_h = dc.GetTextExtent(normal_label)
>         val_text_w, val_text_h = dc.GetTextExtent(value_label)
> 
>         totalwidth = lbl_text_w + val_text_w + self.padding_x + 76
> 
>         # To avoid issues with drawing the control properly, we
>         # always make sure the width is an even number.
>         if totalwidth % 2:
>             totalwidth -= 1
>         totalheight = lbl_text_h + self.padding_y
> 
>         best = wx.Size(totalwidth, totalheight)
> 
>         # Cache the best size so it doesn't need to be calculated again,
>         # at least until some properties of the window change
>         self.CacheBestSize(best)
> 
>         return best
> ```

It worked fine

**Comment by Correct-Syntax** [comment]
I've merged the changes. Great job! 🚀
