### ISSUE TITLE
Proposal: Rename “User Preferences” to “Preferences…”

### ISSUE THREAD

**Issue by JohJakob** [GimelStudio/GimelStudio#56]
There is no real difference between user preferences and settings in Gimel Studio. It would make sense to simplify the term “User Preferences” and just call it “Preferences”. This would also shorten the term in German from “Benutzereinstellungen” to “Einstellungen” which is more desirable.

I would also append an ellipsis (`…`) to the menu item to let the user know that the action requires more actions/opens a dialogue. Both macOS and Blender use “Preferences…”.

**Comment by Correct-Syntax** [comment]
@JohJakob thanks for the suggestion. @iwoithe and I had already discussed this and had settled on "Preferences", so I agree with you. This should be fixed in the Preferences dialog PR or can be fixed after it's merged. 😄 

Proposal accepted! ✅

**Comment by JohJakob** [comment]
I will change all occurrences in the translation files after finishing the German translation.

**Comment by iwoithe** [comment]
> Regarding the ellipse: I also agree

I will update the PR in the next few days. :slightly_smiling_face:

**Comment by Correct-Syntax** [comment]
This was closed with #61
