### ISSUE TITLE
Proposal: Use user-friendly labels for toggles

### ISSUE THREAD

**Issue by JohJakob** [GimelStudio/GimelStudio#59]
Toggles like “Toggle Status Bar” should have a different label based on their state to better indicate what they will do when clicked. For the status bar, this could be “Show Status Bar” and “Hide Status Bar” or it could be replaced with a checkbox toggle like “Auto Render”.

This would also make translations in certain languages (like German) easier because they do not have a convenient term like “toggle” (in German, the only fitting translation is “umschalten”, but it is a bit ambiguous). The same would apply to the help texts.

**Comment by Correct-Syntax** [comment]
I agree. I think it would be good to review all of the text for the menu items and status bar help text for consistency and ease of translation. @iwoithe what is your suggestion for this particular case? I think I like the idea of having a checkbox like Auto Render.

**Comment by iwoithe** [comment]
> review all of the text

Agreed.

> what is your suggestion for this particular case?

I personally prefer the checkbox, however, I get that some people may prefer (updating) text. My opinion is to use a check box by default, but also add a preference like ``Interface > Menu Bar >  Use checkboxes`` (when set to ``False`` use switching text).

**Comment by JohJakob** [comment]
> My opinion is to use a check box by default, but also add a preference like `Interface > Menu Bar > Use checkboxes` (when set to `False` use switching text).

I would go with checkboxes for the MVP. State-dependent labels can be added later, but do not have the highest priority right now in my opinion.
