### ISSUE TITLE
Implement node color property

### ISSUE THREAD

**Issue by Correct-Syntax** [GimelStudio/GimelStudio#93]
Implement a color property for defining a color. Should use the color picker widget from gswidgetkit.

**Comment by yonMaor** [comment]
Hey,
I'd like to help with this issue. 
Can you eleborate further?

**Comment by Correct-Syntax** [comment]
Hi @yonMaor thanks for helping with this issue. Glad to have you here. 😄 

Every node in Gimel Studio (minus the Output node) is written in a python script in the ``nodescripts`` directory. They are like "plugins" or "addons" which use what is called the Python API. The API is basically just a way for these individual node scripts to hook into the renderer and Properties Panel.

A node Property is defined as the widget that directly controls the value of a node via a widget in the Properties Panel. (This is in contrast to the node Parameter that takes an input from another node via a node socket in the Node Graph).

When creating a Property you define both the widget(s) that appear(s) in the Properties panel as well as how the value is returned. 

The base Property class is defined at https://github.com/GimelStudio/GimelStudio/blob/af368dd98ab61d0b28239b7120c8ffc59026c3a7/src/gimelstudio/core/node/property.py#L35 All Node Properties are sub-classes of this base class so this is what you will be working with.

For an example, the ``PositiveIntegerProp`` at https://github.com/GimelStudio/GimelStudio/blob/af368dd98ab61d0b28239b7120c8ffc59026c3a7/src/gimelstudio/core/node/property.py#L107 creates a Number Field widget in the Properties panel and returns a single integer.

You can also take a look at the other Properties defined in that script as more examples.

It is important to know that these Properties are used in the API almost directly as can be seen here: https://github.com/GimelStudio/GimelStudio/blob/af368dd98ab61d0b28239b7120c8ffc59026c3a7/src/nodescripts/corenodes/filter/blur_node.py#L44 This is really powerful as it means that new node Properties can be created outside of the node API as well.

~

So for your issue, you will create a ``ColorProp`` Property which uses the Color Picker widget from [gswidgetkit](https://github.com/GimelStudio/gswidgetkit) and returns the color value (probably as a tuple).

You can save re-writing the boilerplate code by just copying the ``PositiveIntegerProp`` class, renaming it an going from there. 

If you have any questions or need more clarify, feel free to ask.

**Comment by yonMaor** [comment]
Not gonna lie, after a first look this looks a little complicated, but I'll give it a shot over the next few days.
Thanks for the detailed explanation!

**Comment by yonMaor** [comment]
So after taking another look I'm wondering what functionality this widget needs exactly.
I'm also not sure how to interface with [gswidgetkit](https://github.com/GimelStudio/gswidgetkit) (I tried installing it as detailed in the repository, but I seem to already have it installed through Gimel Studios itself)

**Comment by Correct-Syntax** [comment]
@yonMaor yes, gswidgetkit is the set of widgets we are using and the package is installed along with Gimel Studio.

The widgets can be imported just like any class. 

Basically, it is a matter of importing the color picker widget, placing it in the CreateUI method and getting the value from the widget. 

I think I'll do a write up to show you. 🙂

**Comment by Correct-Syntax** [comment]
So, here is a quick untested and unfinished glance at what it would look like:

```python
from gswidgetkit import ColorPicker # I am going from memory so double check this is the correct name of the class! ;)

...

class ColorProp(Property):
    """ Allows the user to select a color. """

    def __init__(self, idname, default=(255, 255, 255, 255), label="", visible=True):
        Property.__init__(self, idname, default, label, visible)

    def CreateUI(self, parent, sizer):
        fold_panel = self.CreateFoldPanel(sizer)
        fold_panel.SetBackgroundColour(wx.Colour("#464646"))

        self.colorpicker= ColorPicker(fold_panel, ...) # Complete the rest of the color picker params with self.default as the default color

        self.AddToFoldPanel(sizer, fold_panel, self.colorpicker, spacing=10)

        # Bind the event for when the color is selected to the WidgetEvent method below

    def WidgetEvent(self, event):
        # Set the value based on the returned value (color)
        self.SetValue(...)
```

Then, you would add this class to the imports in the ``__init__.py`` and ``api/_init__.py``files to make it accessible from the API.

I now realize that the extra params in the ``PositiveIntegerProp`` may have made this look more complex, but basically just fill in what needs to be done described in the comments and this issue should be done. 😃

**Comment by yonMaor** [comment]
I was just starting to figure it out, but thanks for the help! 
Do no other files need to be changed? I've seen some additional files in the nodescripts directory that use the PositiveInteger property, so I was wondering if we need similar files for the color property

**Comment by Correct-Syntax** [comment]
The files in the nodescripts directory are the nodes themselves. So, yes and no. 🙂 You don't have to for this issue, but it would be nice to create a "test case" node that uses the colorprop

**Comment by Correct-Syntax** [comment]
@yonMaor the [checkerboard image](https://github.com/GimelStudio/GimelStudio/blob/master/src/nodescripts/corenodes/input/checkered_image_node.py) node would be a good test case if your interested in doing that. 😄

**Comment by yonMaor** [comment]
Thanks, I'll check it out. 
Sorry that this issue has been taking a while, I've been busy at work. 
I'll probably get to it this weekend

**Comment by Correct-Syntax** [comment]
Hi @yonMaor 🙂

Do you have a timeframe of when you might be able to finish this?

We appreciate your work so far. 👍

**Comment by yonMaor** [comment]
Hey, sorry I didn't get to this, I've been a little busy at work lately.
I'll try to get to it this weekend, but if solving this issue is currently impeding  progress feel free to assign it to someone else

**Comment by yonMaor** [comment]
Hey @Correct-Syntax, 
I think that I've written most of the code for this issue.
Do you have any suggestions for testing it? 
Is there some framework that you've been using for the project?

**Comment by Correct-Syntax** [comment]
Hi @yonMaor, we haven't really used any framework for testing. We primarily do real-life testing with the application itself. 

Probably the best way to test the ``ColorProp`` is to use it in a node. Unfortunately, the checkerboard image node I mentioned previously is no longer working (since I merged some breaking changes). 

So, I created the Color Image node (which is currently hard-coded to be white) which you can use as a test case. https://github.com/GimelStudio/GimelStudio/blob/master/src/nodes/corenodes/input/color_image_node.py

**Comment by yonMaor** [comment]
Seems to be working fine :) 
I'll push the code. Let me know if you have any comments
